name: PushWorldBorder
version: ${project.version}
main: com.youtube.propromp.pushworldborder.PushWorldBorder
api-version: 1.15
commands:
  pwb:
    description: PushWorldBorder by Propromp, Kamesuta
    usage: /pwb help
    permission: pbw
    permission-message: あなたは権限を持っていません。お疲れ様です。
permissions:
  pbw:
    default: op
